### ISSUE TITLE
How do you run Brick examples?

### ISSUE THREAD

**Issue by steveeq1** [pharo-graphics/Brick#8]
Forgive the naive question, but does anyone know how to run the "Brick Examples" object? I am experimenting with Brick and I want to get an idea of how it all works. For instance,

BrBasicExamples play.
BrBasicExamples openInWorld.
BrBasicExamples new openInWorld.

All don't work. It seems to be subclassed from "object", so there is no method caller I can call from a superclass either. is there documentation anywhere because I can't seem to find it.

**Comment by ssor** [comment]
same question

**Comment by tinchodias** [comment]
Hello from 2021. I started to work on this repository this year, and the `BrBasicExamples` is quite empty but there are other examples, clearly.

At this moment, you can do this:
```smalltalk
BrButtonExamples new buttonAndLookWithLabelAndExterior openInNewSpace.
BrToolbarExamples new toolbarInAContainer openInNewSpace.
BrTaggerExamples new newGlamorousTaggerWithExplicitTags openInNewSpace.
BrSimpleListExamples new verticalNumbers openInNewSpace.
BrColumnedListExamples new compositeAllClassesAndPackage openInNewSpace.
BrAnchoredGeometryExamples new movingCorner openInNewSpace.
BrProgressExamples new animatedBarAndTextAbove openInNewSpace.
```

You can look for more examples this way...
1. Search for senders of `gtExample`, which will show you  "<gtExample>" pragma.
2. Filter "Brick", to see only for this repository
3. Manually select oen that answers a BlElement (there are some that only answer an object that is used in another example to feed a BlElement)
4. In a Workspace, send `openInNewSpace` like shown above.

Of course, you can also browse the examples in the [Gtoolkit](https://gtoolkit.com/). 

Also, there is a ToDoList example of use in this repo: https://github.com/pharo-graphics/Spec-Brick but what you create is a Spec UI and then adapted as a Brick UI.

**Comment by tinchodias** [comment]
@steveeq1 @ssor I plan to add a examples subsection to the README before closing this issue.

**Comment by tinchodias** [comment]
Due to conflicts, we are not loading the `*-Examples` packages now: `Brick-Examples` required examples packages in BlocPac and Bloc, and they cause troubles in our NewBrick + NewBloc. We have to resolve this problem because examples can be useful to understand. But, I will close this issue for the moment.
